name = "binary_search"

# The version of your project (required)
version = "0.1.1"

# A short description of your project (optional)
# This will be displayed on the package page if the project is published to
# the Hex package repository.
description = "A simple binary search implementation in Gleam"

# The licences which this project uses, in SPDX format (optional)
licenses = ["Apache-2.0"]

# The source code repository location (optional)
# This will be used in generated documentation and displayed on Hex.
repository = { type = "github", user = "nkpgardose", repo = "binary_search" }

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
